plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'app/helpers/geoblacklight_helper.rb'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
  NewCops: enable

Style/Documentation:
  Enabled: false

# WE WANT TO BRING THESE BACK WHEN WE HAVE THE BANDWIDTH TO REFACTOR
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
