dist: trusty
sudo: required
language: ruby
cache: bundler
addons:
  firefox: latest
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
script:
  - cp config/vars.yml.example config/vars.yml
  - bundle exec rake db:schema:load
  - bundle exec rake ci
