dist: trusty
sudo: required
language: ruby
addons:
  chrome: stable
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 http://localhost &
script:
  - cp config/vars.yml.example config/vars.yml
  - bundle exec rake db:schema:load
  - bundle exec rake ci
