dist: trusty
sudo: required
language: ruby
cache: bundler
addons:
  firefox: latest
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CC_TEST_REPORTER_ID=f0d2e58efd0ddc833f4ffae5c34ce3f034ba4b425bea0f0902952c907156cbba
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - cp config/vars.yml.example config/vars.yml
  - bundle exec rake db:schema:load
  - bundle exec rake ci
  - bundle audit check --ignore CVE-2015-9284 # tempoarily ignore omniauth vulnerability
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TES