load_defaults: 7.33.1
development:
  adapter: solr
  url: <%= Settings.SOLR_URL %>
test: &test
  adapter: solr
  url: <%= Settings.SOLR_URL %>
staging:
  adapter: solr
  url: <%= Settings.SOLR_URL %>
production:
  adapter: solr
  url: <%= Settings.SOLR_URL %>
