
default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= Settings.SQL_HOST %>
  port: <%= Settings.SQL_PORT %>
  database: <%= Settings.SQL_DB %>
  username: <%= Settings.SQL_USER %>
  password: <%= Settings.SQL_PASS %>

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

staging:
  <<: *default
  pool: 5
  timeout: 5000

production:
  <<: *default
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
