
default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['SQL_HOST'] %>
  port: <%= ENV['SQL_PORT'] %>
  database: <%= ENV['SQL_DB'] %>
  username: <%= ENV['SQL_USER'] %>
  password: <%= ENV['SQL_PASS'] %>

development:
  <<: *default
  pool: 5
  timeout: 5000

staging:
  <<: *default
  pool: 5
  timeout: 5000

production:
  <<: *default
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
