# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DEV_SQL_DB'] %>
  pool: 5
  username: <%= ENV['DEV_SQL_USER'] %>
  password: <%= ENV['DEV_SQL_PASS'] %>
  host: <%= ENV['SQL_HOST'] %>
  port: 3306
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['PROD_SQL_DB'] %>
  pool: 5
  username: <%= ENV['PROD_SQL_USER'] %>
  password: <%= ENV['PROD_SQL_PASS'] %>
  host: <%= ENV['SQL_HOST'] %>
  port: 3306
  timeout: 5000

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3