# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'https://geo.nyu.edu/assets/real250.png'

# CartoDB OneClick Service https://cartodb.com/open-in-cartodb/
CARTODB_ONECLICK_LINK: 'http://oneclick.cartodb.com/'

# Download path can be configured using this setting
DOWNLOAD_PATH: "/blacklight_data/cache/downloads"

#Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# Institution deployed at
INSTITUTION: 'NYU'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'fgdc'
  - 'iso19139'
  - 'mods'

PROXY_URL: 'https://ezproxy.library.nyu.edu/login?url=https://maps-restricted.geo.nyu.edu'
RESTRICTED_URL: 'https://maps-restricted.geo.nyu.edu/geoserver/wms'

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 30

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'wfs'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'

# WMS Parameters
WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'