name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SOLR_URL: http://127.0.0.1:8985/solr/sdr-core-test
  SOLR_VERSION: 7.5.0

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Lint
      run: bundle exec rubocop
    - name: Run tests
      run: |
        bundle exec rake db:schema:load
        bundle exec rake ci
    - name: Audit gems
      run: bundle exec bundle-audit check --ignore CVE-2015-9284 # tempoarily ignore omniauth vulnerability
